[project]
name = "novmber"
version = "1.0.0"
description = "Academic ransomware developed for research purposes in the field of Information Security"
authors = [{ name = "Daniel Lima" }]
license = { text = "MIT" }
readme = "README.md"

[tool.pyright]
typeCheckingMode = "strict"
